name: Preprocess Data

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13.2'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn kagglehub # Tambahkan library lain jika diperlukan

    - name: Download Kaggle Dataset
      run: |
        mkdir -p /home/runner/.kaggle
        echo '${{ secrets.KAGGLE_CREDENTIALS }}' > /home/runner/.kaggle/kaggle.json
        chmod 600 /home/runner/.kaggle/kaggle.json
        kaggle datasets download -d utkarshsharma11r/student-mental-health-analysis -p ./namadataset_raw --unzip
      env:
        KAGGLE_CREDENTIALS: ${{ secrets.KAGGLE_CREDENTIALS }} # Anda perlu menambahkan secret ini di GitHub

    - name: Run Preprocessing Script
      run: python ./preprocessing/automate_Kholish-Fauzan.py

    - name: Upload Preprocessed Data as Artifact (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: preprocessed_data
        path: |
          X_train.csv
          X_test.csv
          y_train.csv
          y_test.csv